language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-21.0.2

    # The SDK version used to compile your project
    - android-21
      #- android-19

    # Additional components
    #- extra-android-support
    #- extra-android-m2repository
    #- extra-google-m2reposit
    - extra

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-19
