language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-21.0.2
    
    # The SDK version used to compile your project
    - android-21

    # Additional components
    - extra-android-m2repository
    - extra-google-m2repository

    - sys-img-armeabi-v7a-android-21

notifications:
    email: false

env:
    matrix:
        - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a

before_install:
    - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
    - emulator -avd test -no-skin -no-audio -no-window &

before_script:
    #   - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
    #   - emulator -avd test -no-skin -no-audio -no-window &
    - ./scripts/wait_for_emulator.sh
    - adb shell input keyevent 82 &

